/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WelcomeIndexImport } from './routes/welcome/index'
import { Route as WelcomeSignupImport } from './routes/welcome/signup'
import { Route as WelcomeSigninImport } from './routes/welcome/signin'
import { Route as HomeDashboardImport } from './routes/home/dashboard'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WelcomeIndexRoute = WelcomeIndexImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => rootRoute,
} as any)

const WelcomeSignupRoute = WelcomeSignupImport.update({
  id: '/welcome/signup',
  path: '/welcome/signup',
  getParentRoute: () => rootRoute,
} as any)

const WelcomeSigninRoute = WelcomeSigninImport.update({
  id: '/welcome/signin',
  path: '/welcome/signin',
  getParentRoute: () => rootRoute,
} as any)

const HomeDashboardRoute = HomeDashboardImport.update({
  id: '/home/dashboard',
  path: '/home/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home/dashboard': {
      id: '/home/dashboard'
      path: '/home/dashboard'
      fullPath: '/home/dashboard'
      preLoaderRoute: typeof HomeDashboardImport
      parentRoute: typeof rootRoute
    }
    '/welcome/signin': {
      id: '/welcome/signin'
      path: '/welcome/signin'
      fullPath: '/welcome/signin'
      preLoaderRoute: typeof WelcomeSigninImport
      parentRoute: typeof rootRoute
    }
    '/welcome/signup': {
      id: '/welcome/signup'
      path: '/welcome/signup'
      fullPath: '/welcome/signup'
      preLoaderRoute: typeof WelcomeSignupImport
      parentRoute: typeof rootRoute
    }
    '/welcome/': {
      id: '/welcome/'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/dashboard': typeof HomeDashboardRoute
  '/welcome/signin': typeof WelcomeSigninRoute
  '/welcome/signup': typeof WelcomeSignupRoute
  '/welcome': typeof WelcomeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home/dashboard': typeof HomeDashboardRoute
  '/welcome/signin': typeof WelcomeSigninRoute
  '/welcome/signup': typeof WelcomeSignupRoute
  '/welcome': typeof WelcomeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home/dashboard': typeof HomeDashboardRoute
  '/welcome/signin': typeof WelcomeSigninRoute
  '/welcome/signup': typeof WelcomeSignupRoute
  '/welcome/': typeof WelcomeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home/dashboard'
    | '/welcome/signin'
    | '/welcome/signup'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home/dashboard'
    | '/welcome/signin'
    | '/welcome/signup'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/home/dashboard'
    | '/welcome/signin'
    | '/welcome/signup'
    | '/welcome/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeDashboardRoute: typeof HomeDashboardRoute
  WelcomeSigninRoute: typeof WelcomeSigninRoute
  WelcomeSignupRoute: typeof WelcomeSignupRoute
  WelcomeIndexRoute: typeof WelcomeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeDashboardRoute: HomeDashboardRoute,
  WelcomeSigninRoute: WelcomeSigninRoute,
  WelcomeSignupRoute: WelcomeSignupRoute,
  WelcomeIndexRoute: WelcomeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home/dashboard",
        "/welcome/signin",
        "/welcome/signup",
        "/welcome/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home/dashboard": {
      "filePath": "home/dashboard.tsx"
    },
    "/welcome/signin": {
      "filePath": "welcome/signin.tsx"
    },
    "/welcome/signup": {
      "filePath": "welcome/signup.tsx"
    },
    "/welcome/": {
      "filePath": "welcome/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
