name: Deploy Finnbank Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Finnbank Web
    runs-on: ubuntu-latest
    steps:
      - name: Build and Host
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DCISM_HOST }}
          username: ${{ secrets.DCISM_ACCOUNT }}
          password: ${{ secrets.DCISM_PASSWORD }}
          port: ${{ secrets.DCISM_SSH_PORT }}
          script: |
            cd finnbank.dcism.org/Finnbank-web
            git reset --hard && git clean -fd && git pull origin main
            npm ci
            npm run build
            rm -rf ../dist
            mv ./dist ../
